<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jscompress"
 *
 * Auto generated by Extension Builder 2013-06-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Frontend Performance',
	'description' => 'This extension improves the frontend performance in TYPO3 6.x. Currently adds JS minification via JSMinPlus and some minor improvements.',
	'category' => 'be',
	'author' => 'Felix Nagel',
	'author_email' => 'info@felixnagel.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.1.99',
		),
		'conflicts' => array(
			'scriptmerger' => '',
		),
		'suggests' => array(
		),
	),
);

?>