<?php

namespace FelixNagel\FePerformance\Hook;

/**
 * This file is part of the "fe_performance" Extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

use TYPO3\CMS\Core\Configuration\ExtensionConfiguration;
use TYPO3\CMS\Core\Page\PageRenderer;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * Hook within t3lib\class.t3lib_pagerenderer.php.
 */
class RenderPreProcessHook
{
    /**
     * Exclude files generated by pageRenderer from concatenation
     * We do not want the per page added inline JS to be merged.
     *
     * @param array                             $params
     * @param PageRenderer $pageRenderer
     *
     * @see PageRenderer render-preProcess hook
     */
    public function process(array $params, PageRenderer $pageRenderer)
    {
        $emConfig = GeneralUtility::makeInstance(ExtensionConfiguration::class)->get('fe_performance');

        if (count($params['jsFiles'])) {
            foreach ($params['jsFiles'] as $name => $properties) {
                // Match file pattern for 8.0.0-10.4.2
                // See here (and other places):
                // https://github.com/TYPO3/TYPO3.CMS/blob/9.5/typo3/sysext/frontend/Classes/Page/PageGenerator.php#L875
                // https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L2463
                if (preg_match('/typo3temp\/assets\/js\/[\d|a-z]+\.js/i', $name)) {
                    if ($emConfig['excludeInlineJsFromConcatenation']) {
                        $params['jsFiles'][$name]['excludeFromConcatenation'] = 1;
                    }
                    if ($emConfig['moveInlineJsToFooter']) {
                        $params['jsFiles'][$name]['section'] = PageRenderer::PART_FOOTER;
                    }
                }
            }
        }
    }
}
